### ISSUE TITLE
新功能建议：抠图

### ISSUE THREAD

**Issue by Lu-Qi-777** [noneplugin/nonebot-plugin-imagetools#1]
https://github.com/danielgatis/rembg

用的这个玩意，感觉效果还不错，mq佬可以参考一下0.0

**Comment by MeetWq** [comment]
感觉有点重?而且只能py3.9
或许可以魔改一下

**Comment by Lu-Qi-777** [comment]
确实哎，我自己用的3.9，忘了普适性了←_←
